texni_website/main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from main import views

app_name = 'main'
urlpatterns = [
    path("", views.home, name='home'),
    path("about-us/", views.about_us, name='about_us'),
    path("contact-us/", views.ContactUsView.as_view(), name="contact_us"),
    path("team/", views.team, name="team"),
    path("case-studies/", views.case_studies, name="case_studies"),
    path("careers/", views.careers, name="careers"),
    path("events/", views.events, name="events"),
]

texni_website/texni_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

texni_website/main/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="product-images")

texni_website/main/forms.py
import logging

from django import forms
from django.core.mail import send_mail

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(
        max_length=600,
        widget=forms.Textarea
    )


    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "site@booktime.domain",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )

texni_website/main/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from main import forms



def home(request):
    context = {
        'background': 'background_building.jpg',
    }
    return render(request, 'home.html', context)


def about_us(request):
    context = {
        'background': 'background_paintedwall.jpg',
    }
    return render(request, 'about_us.html', context)


def team(request):
    context = {
        'background': 'background_stainglass.jpg',
    }
    return render(request, 'team.html', context)


def case_studies(request):
    context = {
        'background': 'background_stainglass.jpg',
    }
    return render(request, 'case_studies.html', context)


def careers(request):
    context = {
        'background': 'background_paintedwall.jpg',
    }
    return render(request, 'careers.html', context)


def events(request):
    context = {
        'background': 'background_building.jpg',
    }
    return render(request, 'events.html', context)


class ContactUsView(FormView):
    template_name = "contact_form.html" # this is how it knows which template to use in urls.py
    form_class = forms.ContactForm # this is how it knows which form to use in the template
    success_url = "/"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['background'] ='background_building.jpg'
        return context


    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

texni_website/main/templates/about_us.html
{% extends "base.html" %}

{% block content %}
  <div class="h1 my-5 w-50 text-center mx-auto text-light font-weight-light">
      About us
    </div>
      <div class="w-50 mx-auto text-light font-weight-light">
      <p>We are a group of master data craftsmen who love to solve problems that bring about real value.  All of our consultants have PhDs in a STEM field and are passionate about quality and integrity.  Our aim is always to bring you value that will be felt across your company and for years to come.</p>

      <p> We believe most companies, and data teams, are getting less value from their data because of poor data strategies.  We want to unlock the analytic and decision making power of your data by making it highly performant and reliable.</p>

      <p> See how we have helped companies in the past [link to previous work page] and always feel free to get in touch with us by sending an email to hello@texnidata.com.
      </p>
    </div>
{% endblock content %}

texni_website/main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Texni Data Consulting</title>

    <!-- Bootstrap core CSS -->
    <link href={% static "css/bootstrap.css" %} rel="stylesheet">
    <link href={% static "css/custom.css" %} rel="stylesheet">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" 
                  integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" 
                  crossorigin="anonymous">
    </script>

    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" 
                  integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" 
                  crossorigin="anonymous">
    </script>

  </head>
      <div id="all" style="
      {% with 'images/'|add:background as image_static %}
        background-image: url({% static image_static %});
      {% endwith %}
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      ">

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparant">
      <!-- TODO make this a link -->
      <div id="logo" class="border-0" > <a href="/"><img class="border-0" src="{% static 'images/logo2.png' %}" alt="texni data consulting logo" width=100 height=100></a>
      </div>
      <!-- <div class="h1 text-light font-weight-light" id="name"> -->
      <!--   Texni Consulting -->
      <!-- </div> -->
      <button class="d-md-none btn btn-primary" id="menu-toggle">Toggle Menu</button>

      <button class="navbar-toggler mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0 dropdown-menu-right">
          <li class="nav-item">
            <a class="nav-link text-light" href="mailto:hello@texnidata.com">Email</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="http://www.linkedin.com">LinkedIn</a>
          </li>
          <!-- <li class="nav-item"> -->
          <!--   <a class="nav-link text-light" href="http://www.twitter.com">Twitter</a> -->
          <!-- </li> -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              EN
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">EN</a>
              <a class="dropdown-item" href="#">NL</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>


      <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper" class="mt-0 border-3 border-bottom border-top border-light align-items-stretch bg-transparant list-group list-group-flush lead">

        <span><a href="/" style="color: black" class="list-group-item-action {% if request.path == "/" %}bg-transparant list-group-item-active border-right-0 text-light {% else %} bg-light list-group-item text-dark {% endif %}">
          {% if request.path == "/" %}<i class="fa fa-lg fa-inverse fa-home"></i><span class="pl-3">Home</span>{% else %} <i class="fa fa-lg  fa-home"></i><span class="pl-3">Home</span>{% endif %}
        </a></span>

          <a href="/about-us" style="color: black" class="list-group-item-action text-light {% if request.path == "/about-us/" %}bg-transparant list-group-item-active border-right-0text-light {% else %} bg-light list-group-item text-dark{% endif %}">
          {% if request.path == "/about-us/" %}<i class="fa fa-lg fa-address-card"></i><span class="pl-3">About Us</span>{% else %} <i class="fa fa-lg fa-address-card"></i><span class="pl-3">About Us</span>{% endif %}
          </a>

          <a href="/contact-us" style="color: black" class="list-group-item-action {% if request.path == "/contact-us/" %}bg-transparant list-group-item-active border-right-0 text-light{% else %} bg-light list-group-item  text-dark{% endif %}">
          {% if request.path == "/contact-us/" %}<i class="fa fa-lg fa-inverse fa-phone-volume"></i><span class="pl-3">Contact</span>{% else %} <i class="fa fa-lg  fa-phone-volume"></i><span class="pl-3">Contact</span>{% endif %}
          </a>

          <a href="/team" style="color: black" class="list-group-item-action {% if request.path == "/team/" %}bg-transparant list-group-item-active border-right-0 text-light{% else %} bg-light list-group-item  text-dark{% endif %}">
          {% if request.path == "/team/" %}<i class="fa fa-lg fa-inverse fa-users"></i><span class="pl-3">Team</span>{% else %} <i class="fa fa-lg fa-users"></i><span class="pl-3">Team</span>{% endif %}
          </a>

          <!-- <a href="/case-studies" style="color: black" class="list-group-item-action {% if request.path == "/case-studies/" %}bg-transparant list-group-item-active border-right-0 text-light{% else %} bg-light list-group-item {% endif %}"> -->
          <!-- {% if request.path == "/case-studies/" %}<i class="fa fa-lg fa-inverse fa-search"></i><span class="pl-3">Case Studies</span>{% else %} <i class="fa fa-lg fa-search"></i><span class="pl-3">Case Studies</span>{% endif %} -->
          <!-- </a> -->

          <!-- <a href="/careers" style="color: black" class="list-group-item-action {% if request.path == "/careers/" %}bg-transparant list-group-item-active border-right-0 text-light {% else %} bg-light list-group-item {% endif %}"> -->
          <!-- {% if request.path == "/careers/" %}<i class="fa fa-lg fa-inverse fa-user-md"></i><span class="pl-3">Careers</span>{% else %} <i class="fa fa-lg fa-user-md"></i><span class="pl-3">Careers</span>{% endif %} -->
          <!-- </a> -->

          <a href="/events" style="color: black" class="h-auto list-group-item-action {% if request.path == "/events/" %}bg-transparant list-group-item-active border-right-0 text-light {% else %} bg-light list-group-item {% endif %}">
          {% if request.path == "/events" %}<i class="fa fa-lg fa-inverse fa-calendar-alt"></i><span class="pl-3">Events</span>{% else %} <i class="fa fa-lg fa-calendar-alt"></i><span class="pl-3">Events</span>{% endif %}
          </a>

        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">

          <div class="container-fluid">
            {% block content %}
            {% endblock %}
          </div>
        </div>
        <!-- /#page-content-wrapper -->
      </div>
      <!-- <div id="push"> -->
      <!-- </div> -->

      <!-- /#wrapper -->

      </div>
      <!-- footer -->
      {% block footer %}
        <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
          <div class="container text-center">
            <small>Texni Data Consultancy | Copyright 2019 </small>
          </div>
        </footer>
      {% endblock %}

      <!-- /footer -->

      <!-- Bootstrap core JavaScript -->
      <script src= {% static "jquery/jquery.js" %}></script>
      <script src= {% static "js/bootstrap.bundle.js" %}></script>

      <!-- Menu Toggle Script -->
      <script>
        $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
        });
      </script>
      </div>
  </body>

</html>

texni_website/main/templates/careers.html
{% extends "base.html" %}

{% block content %}
  <div class="h1 my-5 w-50 text-center mx-auto text-light font-weight-light">
    Careers
  </div>
  <div class="w-50 mx-auto text-light font-weight-light">
    <p>We need new team members!</p>
    <p>We are looking for highly skilled and qualified data masters.  We need data scientist and engineers who love data quality and driving value for businesses.  If you think you have what it takes and would enjoy working with us reach out to us at <a class="text-light" href="mailto:recruiting@texnidata.com">recruiting@texnidata.com</a></p>

  </div>
{% endblock content %}

texni_website/main/templates/case_studies.html
{% extends "base.html" %}

{% block content %}
  <div class="h1 my-5 w-50 text-center mx-auto text-light font-weight-light">
    Case Studies
  </div>
  <div class="w-50 mx-auto text-light font-weight-light">
    I think the case studies should be formatted in the following way:
    <ol>
      <li> Business need</li>
      <li> How the data could help</li>
      <li> Outcomes (what we made or did)</li>
      <li> Business impact</li>
      </ol>
  </div>
{% endblock content %}

texni_website/main/templates/contact_form.html
{% extends "base.html" %}

{% block content %}
  <div id="content">
  <div class="h1 w-50 mx-auto text-center text-light font-weight-light">
    Contact Us
  </div>
  <div class="w-50 mx-auto my-auto text-light font-weight-light">
    <p>
      Reach out to us at <a class="text-light" href="mailto:hello@texnidata.com">hello@texnidata.com</a> or use the form below.
    </p>
    <p>
      We would enjoy the chance to sit down with you and talk about your data needs over a cup of coffee.
    </p>

    <form method="POST">
      {% csrf_token %}

      <div class="form-group">
        {{ form.name.label_tag }}
        <input
          type="text"
          class="form-control {% if form.name.errors %}is-invalid{% endif %}"
          id="id_name"
          name="name"
          placeholder="Your name"
          value="{{ form.name.value|default:"" }}" >
          {% if form.name.errors %}
            <div class="invalid-feedback">
              {{ form.name.errors }}
            </div>
      {% endif %}
      </div>

      <div class="form-group">
        {{ form.message.label_tag }}
        <textarea
          class="form-control {% if form.message.errors %} is-invalid {% endif %}"
          id="id_message"
          name="message"
          rows="3">
          {{ form.message.value|default:""}}
        </textarea>
        {% if form.message.errors %}
          <div class="invalid-feedback">
            {{ form.message.errors }}
          </div>
        {% endif %}
      </div>

      <button type="submit" class="btn btn-primary">
        Submit
      </button>

    </form>
  </div>
  </div>
{% endblock content %}

texni_website/main/templates/events.html
{% extends "base.html" %}

{% block content %}
  <div class="h1 my-5 w-50 text-center mx-auto text-light font-weight-light">
    Events
  </div>
  <div class="w-50 mx-auto text-light font-weight-light">
    Tell us what you'd like to be better at, and we'll let you know the next time we're hosting a similar event.
  </div>
{% endblock content %}

texni_website/main/templates/home.html
{% extends "base.html" %}

{% block content %}
  <div class="h1 my-5 w-50 text-center mx-auto text-light font-weight-light">
    Texni Data
  </div>
      <div class="w-50 mx-auto text-light font-weight-light">
        <p>At Texni Data our focus is on making your data a competitive advantage. </p>
        <p> We focus on a wholistic solution to your data needs; first we learn from you what business needs you have, then we help you understand how data can play a role in solving your business problems. </p>
        <p>Next we develop, with you, a data strategy that will unlock the power of your data for years to come.   Lastly, we can bring expert machine learning and analytics to turn your data into actions.</p>
    <p> Your data should be a competitive advantage; we have the skills and tools to help you get the most out of your data.</p>
  </div>
{% endblock content %}

texni_website/main/templates/team.html
{% extends "base.html" %}

{% block content %}
  <div class="h1 my-5 w-50 text-center mx-auto text-light font-weight-light">
    Team
  </div>
      <div class="w-50 mx-auto text-light font-weight-light">
        <p>We need new team members!</p>
        <p>We are looking for highly skilled and qualified data masters.  We need data scientist and engineers who love data quality and driving value for businesses.  If you think you have what it takes and would enjoy working with us reach out to us at <a class="text-light" href="mailto:recruiting@texnidata.com">recruiting@texnidata.com</a></p>
      </div>
{% endblock content %}